spring.application.name=actuator
# expose only safe endpoints
management.endpoints.web.exposure.include=health,info,shutdown

# hide sensitive health details
#management.endpoint.health.show-details=never
#management.endpoint.shutdown.enabled=false

# optional: run actuator on separate port
management.server.port=9090

#spring.security.user.name=admin
#spring.security.user.password=1234